Repository Vancouver-KDD/blog-study, pull requests merged in 2022-10, with the labels that each got.

#34 Create 2022-10-05_SSR-from-scratch.md
  erickim/2022-10-05_SSR-from-scratch.md
Labels: 3주차

#37 Create 2022-10-18_why-are-people-crazy-about-monorepos.md
  erickim/2022-10-18_why-are-people-crazy-about-monorepos.md
Labels: 5주차

#39 [Yongju] Cache-memory
  yongjukwon/2022-10-21-cache-memory.md
  yongjukwon/images/cpu-cache-ram.jpeg
  yongjukwon/images/l1-l2-l3.jpeg
Labels: 6주차

#40 [Jason Park] 5 things I wish I knew better
  jasonpark/2022-10-25-what-after-bootcamp.md
Labels: 6주차
