Repository Vancouver-KDD/blog-study, pull requests merged in 2022-08, with the labels that each got.

#17 [Yongju] Java's thread - 2
  yongjukwon/2022-07-08-java-thread.md
  yongjukwon/2022-07-20-java-thread-2.md
  yongjukwon/images/thread_life_cycle.jpeg
Labels: 7주차

#18 [Eric Kim] Network reverse engineering commit
  erickim/2022-07-22-how-to-reverse-engineer-apps.md
  erickim/images/2022-07-08/android-charles-overview.png
  erickim/images/2022-07-08/browser-devtools-overview.png
  erickim/images/2022-07-08/charles-https-enable-ssl.png
  erickim/images/2022-07-08/charles-https-with-ssl-proxy.png
  erickim/images/2022-07-08/charles-https-without-ssl-proxy.png
  erickim/images/2022-07-08/charles-https_with-ssl-proxy-valid-cert.png
  erickim/images/2022-07-08/chrome-network-inspector.png
  erickim/images/2022-07-08/desktop-application-overview2.png
Labels: 7주차

#20 [Nash] 용도와 목적에 맞게 자바 String 클래스를 사용하는 방법
  nash/2022-07-29-용도와 목적에 맞게 자바 String클래스를 사용하는 방법.md
Labels: 8주차

#21 [Yongju Kwon] Java Concurrency-3 Synchronization
  yongjukwon/2022-07-08-java-concurrency-1-basic.md
  yongjukwon/2022-07-20-java-concurrency-2-thread-management.md
  yongjukwon/2022-08-05-java-concurrency-3-synchronization.md
Labels: 9주차

#22 [Eric Kim] ai-intro
  erickim/2022-08-08-AI-Intro.md
  erickim/images/2022-08-08/ai-intro-1.png
  erickim/images/2022-08-08/ai-intro-10.png
  erickim/images/2022-08-08/ai-intro-11.png
  erickim/images/2022-08-08/ai-intro-12.png
  erickim/images/2022-08-08/ai-intro-13.png
  erickim/images/2022-08-08/ai-intro-14.png
  erickim/images/2022-08-08/ai-intro-15.png
  erickim/images/2022-08-08/ai-intro-16.png
  erickim/images/2022-08-08/ai-intro-17.png
  erickim/images/2022-08-08/ai-intro-18.png
  erickim/images/2022-08-08/ai-intro-19.png
  erickim/images/2022-08-08/ai-intro-2.png
  erickim/images/2022-08-08/ai-intro-3.png
  erickim/images/2022-08-08/ai-intro-4.png
  erickim/images/2022-08-08/ai-intro-5.png
  erickim/images/2022-08-08/ai-intro-6.png
  erickim/images/2022-08-08/ai-intro-7.png
  erickim/images/2022-08-08/ai-intro-8.png
  erickim/images/2022-08-08/ai-intro-9.png
Labels: 9주차

#23 [ Nash] 자바의 람다식(Lambda Expression), 그 존재의 이유에 대한 깊은 고찰
  nash/2022-08-12-자바의 람다식 그 존재의 이유에 대한 고찰.md
Labels: 10주차

#26 [Eric Kim] Unicode and utf-8 character encoding
  erickim/2022-08-22-unicode-and-utf8-character-encoding.md
Labels: 11주차

#25 [Yongju] Java's concurrency-4-Liveness
  yongjukwon/2022-07-20-java-concurrency-2-thread-management.md
  yongjukwon/2022-08-22-java-concurrency-4-liveness.md
  yongjukwon/images/ deadlock.png
  yongjukwon/images/livelock.png
Labels: 11주차

#24 [Somi Jeon] WYSIWYG 에디터, 만다오에서 배우다
  somijeon/2022-07-16-how-https-works.md
  somijeon/2022-08-13-wysiwyg-mandao.md
  somijeon/2022-08-27-why-typscript-1.md
  somijeon/images/mandao_block.png
  somijeon/images/mandao_calendar.png
  somijeon/images/mandao_container.png
  somijeon/images/mandao_group.png
  somijeon/images/mandao_html.png
  somijeon/images/mandao_stack.png
  somijeon/images/var_scope.jpeg
Labels: 10주차

#27 [Nash] 비트코인(Bitcoin)에 대한 고찰 (인문학적인 접근)
  nash/2022-08-26-비트코인에 대한 고찰 (인문학적인 접근).md
Labels: 12주차
